import bleach  # type: ignore[import-untyped]

ALLOWED_TAGS = set(bleach.sanitizer.ALLOWED_TAGS) | {
    "a",
    "abbr",
    "b",
    "i",
    "em",
    "strong",
    "p",
    "br",
    "hr",
    "pre",
    "code",
    "blockquote",
    # Headings
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    # Lists
    "ul",
    "ol",
    "li",
    "dl",
    "dt",
    "dd",
    # Tables
    "table",
    "thead",
    "tbody",
    "tfoot",
    "th",
    "tr",
    "td",
    "caption",
    "colgroup",
    "col",
    # Structural / semantic containers
    "div",
    "span",
    "section",
    "article",
    "header",
    "footer",
    "aside",
    "main",
    "nav",
    "details",
    "summary",
    "small",
    "sub",
    "sup",
    "mark",
    "del",
    "ins",
    "u",
    "s",
    "q",
    "cite",
    "time",
    # Media
    "img",
    "figure",
    "figcaption",
    "picture",
    "source",
    "audio",
    "video",
    "track",
}

ALLOWED_ATTRIBUTES: dict[str, list[str]] = {
    "*": ["class", "id", "title", "lang", "dir"],
    "a": ["href", "title", "rel", "target"],
    "img": ["src", "alt", "title", "width", "height", "srcset", "loading"],
    "picture": [],
    "source": ["src", "srcset", "type", "media", "sizes"],
    "audio": ["src", "controls", "preload", "loop", "muted"],
    "video": [
        "src",
        "controls",
        "preload",
        "loop",
        "muted",
        "poster",
        "width",
        "height",
    ],
    "track": ["src", "kind", "srclang", "label", "default"],
    "td": ["colspan", "rowspan"],
    "th": ["colspan", "rowspan", "scope"],
    "col": ["span"],
    "colgroup": ["span"],
    "time": ["datetime"],
}


# Free email providers
FREE_EMAIL_DOMAINS = {
    "gmail.com",
    "hotmail.com",
    "outlook.com",
    "yahoo.com",
    "live.com",
    "aol.com",
    "icloud.com",
    "msn.com",
    "protonmail.com",
    "zoho.com",
    "mail.com",
    "gmx.com",
    "yandex.com",
    "pm.me",
    "tutanota.com",
    "fastmail.com",
    "inbox.com",
    "hushmail.com",
}
