"""adding icon columns

Revision ID: 19bdaa6208e
Revises: 422da2d0234
Create Date: 2015-07-03 12:09:58.596010

"""

# revision identifiers, used by Alembic.
revision = '19bdaa6208e'
down_revision = '422da2d0234'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('icon', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'icon')
    ### end Alembic commands ###
