"""empty message

Revision ID: 4b5c161e1ced
Revises: None
Create Date: 2015-01-17 01:04:10.187285

"""

# revision identifiers, used by Alembic.
revision = '4b5c161e1ced'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('error_count', sa.Integer(), nullable=True))
    op.add_column('feed', sa.Column('last_error', sa.String(), nullable=True))
    op.add_column('feed', sa.Column('last_refreshed', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('refresh_rate', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_rate')
    op.drop_column('feed', 'last_refreshed')
    op.drop_column('feed', 'last_error')
    op.drop_column('feed', 'error_count')
    ### end Alembic commands ###
