"""new fields for user profile

Revision ID: 594d7410d04f
Revises: 73540b3bf183
Create Date: 2024-12-26 12:18:37.950472

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "594d7410d04f"
down_revision = "73540b3bf183"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("mastodon", sa.String(length=500), nullable=True))
    op.add_column("user", sa.Column("github", sa.String(length=39), nullable=True))
    op.add_column("user", sa.Column("linkedin", sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "linkedin")
    op.drop_column("user", "github")
    op.drop_column("user", "mastodon")
    # ### end Alembic commands ###
